### ISSUE TITLE
Idea: Support for Ploppable RICO packs

### ISSUE THREAD

**Issue by bloodypenguin** [AJ3D/Ploppable-RICO#2]
Just like building themes. If custom asset's author doesn't provide his own XML it should be possible to make a mod that will do that for him

**Comment by AJ3D** [comment]
Yea, I've thought about this. I was thinking about creating a large XML file of settings for  popular Steam assets, and bundling it with the mod.

 In the meantime, there is a large pack of grey box test assets on Steam. 
http://steamcommunity.com/sharedfiles/filedetails/?id=603364420

**Comment by AJ3D** [comment]
RICO settings mod is now available.
