### ISSUE TITLE
Known incompatibility with built-in tools

### ISSUE THREAD

**Issue by Monniasza** [AJ3D/Ploppable-RICO#22]
According to [this spreadsheet](https://docs.google.com/spreadsheets/d/1mVFkj_7ij4FLzKs2QJaONNmb9Z-SRqUeG6xFGqEX1ew/edit#gid=1433988367), PRICO is known to block UI.

**Comment by clausthaler-devel** [comment]
According to the bible Jesus turned water into wine.
