### ISSUE TITLE
Building is turned off

### ISSUE THREAD

**Issue by cptalpdeniz** [AJ3D/Ploppable-RICO#4]
After plopping RICO buildings, some of them turns off. I'm attaching a photo to help identify the problem.
![12322605_10207316890615420_2717039671361000954_o](https://cloud.githubusercontent.com/assets/17345222/15456548/65740614-207c-11e6-8d08-f2db70415f4c.jpg)

**Comment by AJ3D** [comment]
This has been fixed. Thanks for bringing up issues.
